const bcrypt = require('bcryptjs');

// Helper to generate salt and hash sync for seed data
const hashPassword = (password) => bcrypt.hashSync(password, 10);

const mockStore = {
  users: [
    // Patients
    { _id: 'usr_pat1', username: 'patient1', email: 'patient1@gmail.com', password: hashPassword('patient123'), role: 'patient', createdAt: new Date('2026-01-10') },
    
    // Legacy Doctors
    { _id: 'usr_doc1', username: 'dr_arvind', email: 'arvind.sharma@hospital.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-12') },
    { _id: 'usr_doc2', username: 'dr_sneha', email: 'sneha.reddy@hospital.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-13') },
    { _id: 'usr_doc3', username: 'dr_kabir', email: 'kabir.mehta@hospital.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-14') },
    
    // National Doctors (Phase 1)
    { _id: 'usr_doc_del1', username: 'dr_amit', email: 'amit.singh@aiims.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-15') },
    { _id: 'usr_doc_del2', username: 'dr_rashmi', email: 'rashmi.goel@fortis.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-16') },
    { _id: 'usr_doc_mum1', username: 'dr_sandeep', email: 'sandeep.patil@kem.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-17') },
    { _id: 'usr_doc_blr1', username: 'dr_deepa', email: 'deepa.nair@nimhans.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-18') },
    { _id: 'usr_doc_blr2', username: 'dr_vikram', email: 'vikram.hegde@narayana.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-19') },
    { _id: 'usr_doc_hyd1', username: 'dr_srinivas', email: 'srinivas.rao@kims.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-20') },
    { _id: 'usr_doc_hyd2', username: 'dr_anjali', email: 'anjali.prasad@apollo.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-21') },
    { _id: 'usr_doc_hyd3', username: 'dr_venkat', email: 'venkat.raman@care.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-22') },
    { _id: 'usr_doc_chn1', username: 'dr_manian', email: 'manian.k@rajivgandhi.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-23') },
    { _id: 'usr_doc_kol1', username: 'dr_subrata', email: 'subrata.sen@sskm.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-24') },
    { _id: 'usr_doc_pune1', username: 'dr_prakash', email: 'prakash.joshi@sassoon.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-25') },
    { _id: 'usr_doc_ahd1', username: 'dr_gujarat', email: 'bhavesh.patel@civilahd.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-26') },
    
    // National Doctors (Phase 2 - Tier 2/3 Cities)
    { _id: 'usr_doc_lko1', username: 'dr_manoj', email: 'manoj.gupta@sahara.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-27') },
    { _id: 'usr_doc_jpr1', username: 'dr_harsh', email: 'harsh.vardhan@fortisjaipur.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-28') },
    { _id: 'usr_doc_pat1', username: 'dr_shashi', email: 'shashi.kumar@paras.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-29') },
    { _id: 'usr_doc_bpl1', username: 'dr_ritu', email: 'ritu.sharma@aiimsbhopal.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-30') },
    { _id: 'usr_doc_chd1', username: 'dr_gurpreet', email: 'gurpreet.singh@fortischd.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-01-31') },
    { _id: 'usr_doc_gau1', username: 'dr_baruah', email: 'baruah.b@gmch.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-02-01') },
    { _id: 'usr_doc_koc1', username: 'dr_thomas', email: 'thomas.mathew@aster.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-02-02') },
    { _id: 'usr_doc_viz1', username: 'dr_vizag', email: 'prasad.raju@sevenhills.com', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-02-03') },

    // Legacy Hospitals
    { _id: 'usr_hosp1', username: 'metro_mumbai', email: 'contact@metromumbai.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-05') },
    { _id: 'usr_hosp2', username: 'green_bangalore', email: 'admin@greenvalley.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-06') },
    { _id: 'usr_hosp3', username: 'apex_delhi', email: 'info@apexhealthcare.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-07') },
    
    // National Hospitals (Phase 1)
    { _id: 'usr_hosp_del_govt1', username: 'aiims_delhi', email: 'contact@aiims.edu', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-08') },
    { _id: 'usr_hosp_del_pvt1', username: 'fortis_delhi', email: 'info@fortisescorts.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-09') },
    { _id: 'usr_hosp_mum_govt1', username: 'kem_mumbai', email: 'admin@kem.edu', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-10') },
    { _id: 'usr_hosp_blr_govt1', username: 'nimhans_blr', email: 'registrar@nimhans.ac.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-11') },
    { _id: 'usr_hosp_blr_pvt1', username: 'narayana_blr', email: 'contact@narayanahealth.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-12') },
    { _id: 'usr_hosp_hyd_govt1', username: 'nims_hyd', email: 'director@nims.edu.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-13') },
    { _id: 'usr_hosp_hyd_pvt1', username: 'care_hyd', email: 'contact@carehyderabad.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-14') },
    { _id: 'usr_hosp_hyd_pvt2', username: 'apollo_hyd', email: 'admin@apollohyderguda.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-15') },
    { _id: 'usr_hosp_hyd_pvt3', username: 'kims_hyd', email: 'info@kimshospitals.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-16') },
    { _id: 'usr_hosp_chn_govt1', username: 'rgggh_chennai', email: 'dean@rgggh.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-17') },
    { _id: 'usr_hosp_chn_pvt1', username: 'apollo_chennai', email: 'greams@apollohospitals.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-18') },
    { _id: 'usr_hosp_kol_govt1', username: 'sskm_kolkata', email: 'principal@sskm.gov.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-19') },
    { _id: 'usr_hosp_pune_govt1', username: 'sassoon_pune', email: 'dean@sassoonpune.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-20') },
    { _id: 'usr_hosp_ahd_govt1', username: 'civil_ahmedabad', email: 'info@civilhospitalahd.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-21') },

    // National Hospitals (Phase 2 - Tier 2/3 Cities)
    { _id: 'usr_hosp_lko_govt1', username: 'sgpgi_lko', email: 'director@sgpgi.ac.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-22') },
    { _id: 'usr_hosp_lko_pvt1', username: 'sahara_lko', email: 'contact@saharahospital.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-23') },
    { _id: 'usr_hosp_jpr_govt1', username: 'sms_jaipur', email: 'admin@smshospital.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-24') },
    { _id: 'usr_hosp_jpr_pvt1', username: 'fortis_jaipur', email: 'jaipur@fortis.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-25') },
    { _id: 'usr_hosp_pat_govt1', username: 'pmch_patna', email: 'dean@pmch.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-26') },
    { _id: 'usr_hosp_pat_pvt1', username: 'paras_patna', email: 'info@parashmri.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-27') },
    { _id: 'usr_hosp_bpl_govt1', username: 'aiims_bhopal', email: 'info@aiimsbhopal.edu.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-28') },
    { _id: 'usr_hosp_chd_govt1', username: 'pgimer_chd', email: 'dean@pgimer.edu.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-29') },
    { _id: 'usr_hosp_chd_pvt1', username: 'fortis_mohali', email: 'mohali@fortis.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-30') },
    { _id: 'usr_hosp_gau_govt1', username: 'gmch_guwahati', email: 'principal@gmchportal.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-01-31') },
    { _id: 'usr_hosp_koc_pvt1', username: 'aster_kochi', email: 'kochi@asterhospital.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-01') },
    { _id: 'usr_hosp_viz_pvt1', username: 'sevenhills_vizag', email: 'vizag@sevenhills.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-02') },

    // Phase 3 State-wide District Expansion - Hospital Admins
    { _id: 'usr_hosp_vad_govt1', username: 'ssg_vadodara', email: 'contact@ssgbh.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-03') },
    { _id: 'usr_hosp_vad_pvt1', username: 'sterling_vadodara', email: 'info@sterlingvadodara.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-04') },
    { _id: 'usr_hosp_ind_govt1', username: 'myh_indore', email: 'admin@myhospital.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-05') },
    { _id: 'usr_hosp_ind_pvt1', username: 'bombay_indore', email: 'info@bombayhospitalindore.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-06') },
    { _id: 'usr_hosp_cbt_govt1', username: 'cmch_coimbatore', email: 'dean@cmchcoimbatore.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-07') },
    { _id: 'usr_hosp_cbt_pvt1', username: 'ramakrishna_coimbatore', email: 'contact@sriramakrishnahospital.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-08') },
    { _id: 'usr_hosp_nag_govt1', username: 'gmch_nagpur', email: 'registrar@gmchnagpur.gov.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-09') },
    { _id: 'usr_hosp_nag_pvt1', username: 'kingsway_nagpur', email: 'info@kingswayhospitals.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-10') },
    { _id: 'usr_hosp_bbs_govt1', username: 'aiims_bhubaneswar', email: 'admin@aiimsbhubaneswar.edu.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-11') },
    { _id: 'usr_hosp_bbs_pvt1', username: 'sum_bhubaneswar', email: 'info@sumultimatemedicare.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-12') },
    { _id: 'usr_hosp_srt_govt1', username: 'smimer_surat', email: 'dean@smimer.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-13') },
    { _id: 'usr_hosp_srt_pvt1', username: 'sunshine_surat', email: 'contact@sunshinesurat.com', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-14') },
    { _id: 'usr_hosp_and_pvt1', username: 'skh_anand', email: 'info@charutarhealth.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-15') },
    { _id: 'usr_hosp_tha_govt1', username: 'csm_thane', email: 'dean@csmhospitalthane.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-16') },
    { _id: 'usr_hosp_kln_govt1', username: 'kdmc_kalyan', email: 'admin@kdmchospital.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-17') },
    { _id: 'usr_hosp_mys_govt1', username: 'kr_mysore', email: 'contact@mysoremedicalcollege.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-18') },
    { _id: 'usr_hosp_hub_govt1', username: 'kims_hubli', email: 'director@kimshubli.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-19') },
    { _id: 'usr_hosp_wgl_govt1', username: 'mgm_warangal', email: 'superintendent@mgmwarangal.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-20') },
    { _id: 'usr_hosp_vjw_govt1', username: 'ggh_vijayawada', email: 'admin@gghvijayawada.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-21') },
    { _id: 'usr_hosp_mdr_govt1', username: 'rajaji_madurai', email: 'dean@grhmdr.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-22') },
    { _id: 'usr_hosp_jod_govt1', username: 'snmc_jodhpur', email: 'contact@snmcjodhpur.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-23') },
    { _id: 'usr_hosp_ajm_govt1', username: 'jln_ajmer', email: 'dean@jlnmcajmer.org', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-24') },
    { _id: 'usr_hosp_gkp_govt1', username: 'brd_gorakhpur', email: 'principal@brdmc.ac.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-25') },
    { _id: 'usr_hosp_vns_govt1', username: 'bhu_varanasi', email: 'director.ims@bhu.ac.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-26') },
    { _id: 'usr_hosp_cal_govt1', username: 'gmc_kozhikode', email: 'dean@gmckozhikode.gov.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-27') },
    { _id: 'usr_hosp_tcr_govt1', username: 'gmc_thrissur', email: 'dean@gmcthrissur.gov.in', password: hashPassword('hospital123'), role: 'hospital', createdAt: new Date('2026-02-28') },

    // Phase 3 State-wide District Expansion - Specialist Doctors
    { _id: 'usr_doc_vad1', username: 'dr_patel_vad', email: 'amit.patel@ssg.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-01') },
    { _id: 'usr_doc_ind1', username: 'dr_vyas_ind', email: 'sanjay.vyas@myh.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-02') },
    { _id: 'usr_doc_cbt1', username: 'dr_raj_cbt', email: 'rajesh.k@cmch.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-03') },
    { _id: 'usr_doc_nag1', username: 'dr_desh_nag', email: 'suresh.d@gmch.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-04') },
    { _id: 'usr_doc_bbs1', username: 'dr_misra_bbs', email: 'alok.misra@aiims.edu.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-05') },
    { _id: 'usr_doc_srt1', username: 'dr_desai_srt', email: 'karan.desai@smimer.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-06') },
    { _id: 'usr_doc_and1', username: 'dr_shah_and', email: 'anil.shah@skh.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-07') },
    { _id: 'usr_doc_tha1', username: 'dr_shinde_tha', email: 'rahul.shinde@csm.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-08') },
    { _id: 'usr_doc_kln1', username: 'dr_kulkarni_kln', email: 'vijay.k@kdmc.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-09') },
    { _id: 'usr_doc_mys1', username: 'dr_gowda_mys', email: 'chandra.g@kr.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-10') },
    { _id: 'usr_doc_hub1', username: 'dr_patil_hub', email: 'guru.patil@kims.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-11') },
    { _id: 'usr_doc_wgl1', username: 'dr_chary_wgl', email: 'krishna.c@mgm.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-12') },
    { _id: 'usr_doc_vjw1', username: 'dr_prasad_vjw', email: 'venkat.p@ggh.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-13') },
    { _id: 'usr_doc_mdr1', username: 'dr_pandian_mdr', email: 'suresh.p@grh.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-14') },
    { _id: 'usr_doc_jod1', username: 'dr_rathore_jod', email: 'sunil.r@snmc.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-15') },
    { _id: 'usr_doc_ajm1', username: 'dr_sharma_ajm', email: 'ajay.s@jln.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-16') },
    { _id: 'usr_doc_gkp1', username: 'dr_mishra_gkp', email: 'devendra.m@brdmc.org', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-17') },
    { _id: 'usr_doc_vns1', username: 'dr_pandey_vns', email: 'anil.p@bhu.ac.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-18') },
    { _id: 'usr_doc_cal1', username: 'dr_nair_cal', email: 'pradeep.n@gmc.gov.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-19') },
    { _id: 'usr_doc_tcr1', username: 'dr_menon_tcr', email: 'haridas.m@gmc.gov.in', password: hashPassword('doctor123'), role: 'doctor', createdAt: new Date('2026-03-20') }
  ],
  patients: [
    {
      _id: 'pat1',
      userId: 'usr_pat1',
      name: 'Rohan Verma',
      age: 32,
      gender: 'Male',
      phone: '9876543210',
      location: 'Mumbai',
      incomeRange: 'low',
      healthProblem: 'Chest discomfort and shortness of breath during walk',
      insuranceDetails: 'State Low Income Scheme Card',
      abhaId: '91-2083-4859-1039',
      governmentSchemesEligible: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      createdAt: new Date('2026-01-10')
    }
  ],
  hospitals: [
    // MUMBAI
    {
      _id: 'hosp1',
      userId: 'usr_hosp1',
      name: 'Metro City Multispecialty Hospital',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Plot 42, Bandra Reclamation, Bandra West',
      city: 'Mumbai',
      coordinates: { lat: 19.0544, lng: 72.8294 },
      departments: ['Cardiology', 'Orthopedics', 'General Medicine', 'Neurology'],
      minPrice: 150,
      maxPrice: 600,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '022-26402222',
      rating: 4.6,
      reviews: [{ patientName: 'Amit Shah', comment: 'Excellent and quick cardiac care.', rating: 5, createdAt: new Date('2026-02-15') }],
      createdAt: new Date('2026-01-05')
    },
    {
      _id: 'hosp_mum_govt1',
      userId: 'usr_hosp_mum_govt1',
      name: 'KEM Hospital & Research Centre',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Acharya Donde Marg, Parel',
      city: 'Mumbai',
      coordinates: { lat: 19.0024, lng: 72.8421 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 100,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '022-24107000',
      rating: 4.4,
      reviews: [{ patientName: 'Suresh Patil', comment: 'Free treatment under Ayushman card. Highly helpful.', rating: 5, createdAt: new Date('2026-03-10') }],
      createdAt: new Date('2026-01-10')
    },

    // BANGALORE
    {
      _id: 'hosp2',
      userId: 'usr_hosp2',
      name: 'Green Valley General & Pediatric Hospital',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: '12th Main Road, HAL 2nd Stage, Indiranagar',
      city: 'Bangalore',
      coordinates: { lat: 12.9719, lng: 77.5946 },
      departments: ['Pediatrics', 'General Medicine', 'Dermatology', 'Gynaecology'],
      minPrice: 250,
      maxPrice: 800,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: false,
      bloodAvailable: true,
      ambulanceContact: '080-45129999',
      rating: 4.3,
      reviews: [{ patientName: 'Karthik Raja', comment: 'Great doctors for kids. Very understanding.', rating: 5, createdAt: new Date('2026-04-10') }],
      createdAt: new Date('2026-01-06')
    },
    {
      _id: 'hosp_blr_govt1',
      userId: 'usr_hosp_blr_govt1',
      name: 'NIMHANS Neuro & Psychiatric Hospital',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Hosur Road, Near Lakkasandra',
      city: 'Bangalore',
      coordinates: { lat: 12.9429, lng: 77.5975 },
      departments: ['Neurology', 'General Medicine'],
      minPrice: 50,
      maxPrice: 200,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: false,
      ambulanceContact: '080-26995000',
      rating: 4.7,
      reviews: [{ patientName: 'Harish Gowda', comment: 'Top class neurology treatment at subsidised costs.', rating: 5, createdAt: new Date('2026-04-18') }],
      createdAt: new Date('2026-01-11')
    },
    {
      _id: 'hosp_blr_pvt1',
      userId: 'usr_hosp_blr_pvt1',
      name: 'Narayana Health City',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: '258/A, Bommasandra Industrial Area, Anekal',
      city: 'Bangalore',
      coordinates: { lat: 12.8123, lng: 77.6912 },
      departments: ['Cardiology', 'Orthopedics', 'Pediatrics', 'Neurology', 'General Medicine'],
      minPrice: 300,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '080-22442255',
      rating: 4.6,
      reviews: [{ patientName: 'Lakshmi Devi', comment: 'Cashless cardiac checkup done seamlessly.', rating: 5, createdAt: new Date('2026-04-25') }],
      createdAt: new Date('2026-01-12')
    },

    // DELHI
    {
      _id: 'hosp3',
      userId: 'usr_hosp3',
      name: 'Apex Super Specialty Healthcare',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Pusa Road, Opp. Metro Pillar 115, Karol Bagh',
      city: 'Delhi',
      coordinates: { lat: 28.6304, lng: 77.2177 },
      departments: ['Neurology', 'Orthopedics', 'Cardiology', 'Dermatology', 'General Medicine'],
      minPrice: 500,
      maxPrice: 1500,
      governmentSchemes: ['CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: false,
      ambulanceContact: '011-48228888',
      rating: 4.5,
      reviews: [{ patientName: 'Sunita Sharma', comment: 'Highly professional neurologist.', rating: 5, createdAt: new Date('2026-04-02') }],
      createdAt: new Date('2026-01-07')
    },
    {
      _id: 'hosp_del_govt1',
      userId: 'usr_hosp_del_govt1',
      name: 'AIIMS (All India Institute of Medical Sciences)',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Ansari Nagar, Ring Road',
      city: 'Delhi',
      coordinates: { lat: 28.5672, lng: 77.2100 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '011-26588500',
      rating: 4.8,
      reviews: [{ patientName: 'Aman Yadav', comment: 'Best doctors in India. Cashless Ayushman coverage.', rating: 5, createdAt: new Date('2026-04-12') }],
      createdAt: new Date('2026-01-08')
    },
    {
      _id: 'hosp_del_pvt1',
      userId: 'usr_hosp_del_pvt1',
      name: 'Fortis Escorts Heart Institute',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Okhla Road, New Delhi',
      city: 'Delhi',
      coordinates: { lat: 28.5604, lng: 77.2735 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine'],
      minPrice: 400,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '011-47135000',
      rating: 4.7,
      reviews: [{ patientName: 'Neetu Goel', comment: 'Superb pediatric cardiology team.', rating: 5, createdAt: new Date('2026-04-15') }],
      createdAt: new Date('2026-01-09')
    },

    // HYDERABAD
    {
      _id: 'hosp_hyd1',
      userId: 'usr_hosp_hyd1',
      name: 'CARE Hospitals, Gachibowli',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Old Mumbai Highway, Near Westin Hotel, Gachibowli',
      city: 'Hyderabad',
      coordinates: { lat: 17.4424, lng: 78.3752 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 200,
      maxPrice: 600,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '040-61111111',
      rating: 4.7,
      reviews: [{ patientName: 'Nagesh Kumar', comment: 'Excellent pediatric emergency response and clean facilities.', rating: 5, createdAt: new Date('2026-05-10') }],
      createdAt: new Date('2026-01-08')
    },
    {
      _id: 'hosp_hyd2',
      userId: 'usr_hosp_hyd2',
      name: 'Apollo Hospitals, Hyderguda',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Hyderguda, Near Old MLA Quarters',
      city: 'Hyderabad',
      coordinates: { lat: 17.3986, lng: 78.4822 },
      departments: ['Pediatrics', 'General Medicine', 'Cardiology', 'Neurology', 'Gynaecology'],
      minPrice: 150,
      maxPrice: 500,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '040-23231380',
      rating: 4.8,
      reviews: [{ patientName: 'Vijay Laxmi', comment: 'Prompt CGHS card approvals and expert pediatrician consultation.', rating: 5, createdAt: new Date('2026-05-15') }],
      createdAt: new Date('2026-01-09')
    },
    {
      _id: 'hosp_hyd3',
      userId: 'usr_hosp_hyd3',
      name: 'KIMS Hospitals, Secunderabad',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: '1-8-31/1, Minister Road, Begumpet',
      city: 'Hyderabad',
      coordinates: { lat: 17.4334, lng: 78.4878 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics', 'Cardiology', 'Neurology'],
      minPrice: 200,
      maxPrice: 800,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: false,
      ambulanceContact: '040-44885000',
      rating: 4.5,
      reviews: [{ patientName: 'Radha Mohan', comment: 'Very professional clinical environment and affordable rates.', rating: 4, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-01-10')
    },
    {
      _id: 'hosp_hyd_govt1',
      userId: 'usr_hosp_hyd_govt1',
      name: 'NIMS (Nizam\'s Institute of Medical Sciences)',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Panjagutta, Hyderabad',
      city: 'Hyderabad',
      coordinates: { lat: 17.4246, lng: 78.4520 },
      departments: ['Neurology', 'Cardiology', 'Orthopedics', 'General Medicine'],
      minPrice: 50,
      maxPrice: 250,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '040-23489000',
      rating: 4.3,
      reviews: [{ patientName: 'Kiran Goud', comment: 'Government empanelled. Aarogyasri accepted.', rating: 4, createdAt: new Date('2026-05-25') }],
      createdAt: new Date('2026-01-13')
    },

    // CHENNAI
    {
      _id: 'hosp_chn_govt1',
      userId: 'usr_hosp_chn_govt1',
      name: 'Rajiv Gandhi Government General Hospital',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'E.V.R. Periyar Salai, Park Town',
      city: 'Chennai',
      coordinates: { lat: 13.0805, lng: 80.2741 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '044-25305000',
      rating: 4.5,
      reviews: [{ patientName: 'Murugan K', comment: 'Largest govt hospital. Free clinical care.', rating: 5, createdAt: new Date('2026-03-15') }],
      createdAt: new Date('2026-01-17')
    },
    {
      _id: 'hosp_chn_pvt1',
      userId: 'usr_hosp_chn_pvt1',
      name: 'Apollo Hospitals, Greams Road',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: '21, Greams Lane, Off Greams Road',
      city: 'Chennai',
      coordinates: { lat: 13.0601, lng: 80.2520 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 400,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '044-28290200',
      rating: 4.8,
      reviews: [{ patientName: 'Ramesh Krishnan', comment: 'Exceptional cardiologists.', rating: 5, createdAt: new Date('2026-03-22') }],
      createdAt: new Date('2026-01-18')
    },

    // KOLKATA
    {
      _id: 'hosp_kol_govt1',
      userId: 'usr_hosp_kol_govt1',
      name: 'IPGMER and SSKM Hospital',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: '244, Acharya Jagadish Chandra Bose Road',
      city: 'Kolkata',
      coordinates: { lat: 22.5391, lng: 88.3444 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '033-22231520',
      rating: 4.6,
      reviews: [{ patientName: 'Joydip Das', comment: 'Cashless Swasthya Sathi treatment done.', rating: 5, createdAt: new Date('2026-04-05') }],
      createdAt: new Date('2026-01-19')
    },

    // PUNE
    {
      _id: 'hosp_pune_govt1',
      userId: 'usr_hosp_pune_govt1',
      name: 'Sassoon General Hospital',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Station Road, Near Pune Railway Station',
      city: 'Pune',
      coordinates: { lat: 18.5276, lng: 73.8732 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 100,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '020-26128000',
      rating: 4.3,
      reviews: [{ patientName: 'Anil Kulkarni', comment: 'Helpful doctors for basic pediatric care.', rating: 4, createdAt: new Date('2026-04-12') }],
      createdAt: new Date('2026-01-20')
    },

    // AHMEDABAD
    {
      _id: 'hosp_ahd_govt1',
      userId: 'usr_hosp_ahd_govt1',
      name: 'Civil Hospital, Ahmedabad',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Asarwa, Near Haripura',
      city: 'Ahmedabad',
      coordinates: { lat: 23.0512, lng: 72.6025 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '079-22683721',
      rating: 4.5,
      reviews: [{ patientName: 'Mahesh Patel', comment: 'Very large campus. Free clinical support with PMJAY card.', rating: 5, createdAt: new Date('2026-04-20') }],
      createdAt: new Date('2026-01-21')
    },

    // LUCKNOW
    {
      _id: 'hosp_lko_govt1',
      userId: 'usr_hosp_lko_govt1',
      name: 'SGPGIMS (Sanjay Gandhi Post Graduate Institute)',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Raebareli Road, Lucknow',
      city: 'Lucknow',
      coordinates: { lat: 26.7423, lng: 80.9388 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'General Medicine'],
      minPrice: 50,
      maxPrice: 300,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0522-2668004',
      rating: 4.6,
      reviews: [{ patientName: 'Alok Gupta', comment: 'Top-class research institute and treatments.', rating: 5, createdAt: new Date('2026-05-02') }],
      createdAt: new Date('2026-01-22')
    },
    {
      _id: 'hosp_lko_pvt1',
      userId: 'usr_hosp_lko_pvt1',
      name: 'Sahara Hospital, Lucknow',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Viraj Khand, Gomti Nagar',
      city: 'Lucknow',
      coordinates: { lat: 26.8524, lng: 81.0023 },
      departments: ['Pediatrics', 'General Medicine', 'Cardiology'],
      minPrice: 400,
      maxPrice: 800,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0522-6780001',
      rating: 4.5,
      reviews: [{ patientName: 'Sudha Singh', comment: 'Very professional pediatric care.', rating: 4, createdAt: new Date('2026-05-11') }],
      createdAt: new Date('2026-01-23')
    },

    // JAIPUR
    {
      _id: 'hosp_jpr_govt1',
      userId: 'usr_hosp_jpr_govt1',
      name: 'SMS Hospital (Sawai Man Singh)',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Jawahar Lal Nehru Marg, Jaipur',
      city: 'Jaipur',
      coordinates: { lat: 26.9012, lng: 75.8155 },
      departments: ['General Medicine', 'Cardiology', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0141-2560291',
      rating: 4.4,
      reviews: [{ patientName: 'Rajesh Sharma', comment: 'Huge state hospital, Chiranjeevi Yojana empanelled.', rating: 4, createdAt: new Date('2026-05-18') }],
      createdAt: new Date('2026-01-24')
    },
    {
      _id: 'hosp_jpr_pvt1',
      userId: 'usr_hosp_jpr_pvt1',
      name: 'Fortis Escorts Hospital, Jaipur',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Jawaharlal Nehru Marg, Malviya Nagar',
      city: 'Jaipur',
      coordinates: { lat: 26.8488, lng: 75.8035 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine'],
      minPrice: 500,
      maxPrice: 1000,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0141-2547000',
      rating: 4.7,
      reviews: [{ patientName: 'Priya Meena', comment: 'Affordable child diagnostics and top pediatric specialists.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-01-25')
    },

    // PATNA
    {
      _id: 'hosp_pat_govt1',
      userId: 'usr_hosp_pat_govt1',
      name: 'PMCH (Patna Medical College and Hospital)',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Ashok Rajpath, Patna',
      city: 'Patna',
      coordinates: { lat: 25.6201, lng: 85.1512 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology'],
      minPrice: 0,
      maxPrice: 30,
      governmentSchemes: ['Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0612-2300341',
      rating: 4.1,
      reviews: [{ patientName: 'Ravi Kumar', comment: 'Free treatment under government schemes.', rating: 4, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-01-26')
    },
    {
      _id: 'hosp_pat_pvt1',
      userId: 'usr_hosp_pat_pvt1',
      name: 'Paras HMRI Hospital, Patna',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'NH-30, Bailey Road, Raja Bazar',
      city: 'Patna',
      coordinates: { lat: 25.6111, lng: 85.0888 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Neurology'],
      minPrice: 400,
      maxPrice: 900,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0612-7107777',
      rating: 4.5,
      reviews: [{ patientName: 'Sanjana Kumari', comment: 'Experienced child specialist and good ICU care.', rating: 5, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-01-27')
    },

    // BHOPAL
    {
      _id: 'hosp_bpl_govt1',
      userId: 'usr_hosp_bpl_govt1',
      name: 'AIIMS Bhopal',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Saket Nagar, Bhopal',
      city: 'Bhopal',
      coordinates: { lat: 23.2045, lng: 77.4523 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 10,
      maxPrice: 100,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0755-2900697',
      rating: 4.6,
      reviews: [{ patientName: 'Deepak Raj', comment: 'Cashless PMJAY treatment. Very systematic.', rating: 5, createdAt: new Date('2026-05-26') }],
      createdAt: new Date('2026-01-28')
    },

    // CHANDIGARH
    {
      _id: 'hosp_chd_govt1',
      userId: 'usr_hosp_chd_govt1',
      name: 'PGIMER Chandigarh',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Sector 12, Chandigarh',
      city: 'Chandigarh',
      coordinates: { lat: 30.7624, lng: 76.7766 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'General Medicine'],
      minPrice: 50,
      maxPrice: 200,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0172-2747585',
      rating: 4.8,
      reviews: [{ patientName: 'Harpal Singh', comment: 'World class doctors. Excellent government facility.', rating: 5, createdAt: new Date('2026-05-18') }],
      createdAt: new Date('2026-01-29')
    },
    {
      _id: 'hosp_chd_pvt1',
      userId: 'usr_hosp_chd_pvt1',
      name: 'Fortis Hospital, Mohali',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Sector 62, Phase VIII, Sahibzada Ajit Singh Nagar, Mohali',
      city: 'Chandigarh',
      coordinates: { lat: 30.6924, lng: 76.7323 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Orthopedics'],
      minPrice: 600,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0172-5021222',
      rating: 4.7,
      reviews: [{ patientName: 'Kiran Deep', comment: 'Best child cardiology facility in the region.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-01-30')
    },

    // GUWAHATI
    {
      _id: 'hosp_gau_govt1',
      userId: 'usr_hosp_gau_govt1',
      name: 'GMCH (Guwahati Medical College)',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Indrapur, Bhangagarh, Guwahati',
      city: 'Guwahati',
      coordinates: { lat: 26.1524, lng: 91.7688 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0361-2134500',
      rating: 4.4,
      reviews: [{ patientName: 'Baruah Gogoi', comment: 'Empanelled with Ayushman Asom scheme. Satisfactory care.', rating: 4, createdAt: new Date('2026-05-15') }],
      createdAt: new Date('2026-01-31')
    },

    // KOCHI
    {
      _id: 'hosp_koc_pvt1',
      userId: 'usr_hosp_koc_pvt1',
      name: 'Aster Medcity, Kochi',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Kuttisahib Road, Cheranalloor, Kochi',
      city: 'Kochi',
      coordinates: { lat: 10.0488, lng: 76.2735 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 500,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0484-6699999',
      rating: 4.8,
      reviews: [{ patientName: 'Mathew Thomas', comment: 'Extremely clean environment and very good pediatrics ward.', rating: 5, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-02-01')
    },

    // VISAKHAPATNAM
    {
      _id: 'hosp_viz_pvt1',
      userId: 'usr_hosp_viz_pvt1',
      name: 'SevenHills Hospital, Vizag',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Rockdale Layout, Ramnagar, Visakhapatnam',
      city: 'Visakhapatnam',
      coordinates: { lat: 17.7212, lng: 83.3033 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Neurology'],
      minPrice: 300,
      maxPrice: 800,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0891-2708090',
      rating: 4.6,
      reviews: [{ patientName: 'Prasad Raju', comment: 'Quick Aarogyasri approvals and good ICU ward support.', rating: 5, createdAt: new Date('2026-05-25') }],
      createdAt: new Date('2026-02-02')
    },

    // VADODARA
    {
      _id: 'hosp_vad_govt1',
      userId: 'usr_hosp_vad_govt1',
      name: 'Sir Sayajirao General (SSG) Hospital',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Jail Road (Indira Avenue), Vadodara',
      city: 'Vadodara',
      coordinates: { lat: 22.3072, lng: 73.1812 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0265-2424424',
      rating: 4.4,
      reviews: [{ patientName: 'Nitin Patel', comment: 'Free treatment and good OPD services.', rating: 4, createdAt: new Date('2026-05-10') }],
      createdAt: new Date('2026-02-03')
    },
    {
      _id: 'hosp_vad_pvt1',
      userId: 'usr_hosp_vad_pvt1',
      name: 'Sterling Hospital, Vadodara',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Near Akota Stadium, Vadodara',
      city: 'Vadodara',
      coordinates: { lat: 22.2929, lng: 73.1650 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
      minPrice: 300,
      maxPrice: 900,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0265-2354455',
      rating: 4.6,
      reviews: [{ patientName: 'Kirit Shah', comment: 'Highly clean and professional cardiology care.', rating: 5, createdAt: new Date('2026-05-15') }],
      createdAt: new Date('2026-02-04')
    },

    // INDORE
    {
      _id: 'hosp_ind_govt1',
      userId: 'usr_hosp_ind_govt1',
      name: 'Maharaja Yeshwantrao Hospital (MYH)',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Residency Area, Indore',
      city: 'Indore',
      coordinates: { lat: 22.7196, lng: 75.8762 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0731-2527301',
      rating: 4.3,
      reviews: [{ patientName: 'Anoop Vyas', comment: 'Very cheap consulting and helpful staff.', rating: 4, createdAt: new Date('2026-05-18') }],
      createdAt: new Date('2026-02-05')
    },
    {
      _id: 'hosp_ind_pvt1',
      userId: 'usr_hosp_ind_pvt1',
      name: 'Bombay Hospital, Indore',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Eastern Ring Road, Vijay Nagar, Indore',
      city: 'Indore',
      coordinates: { lat: 22.7533, lng: 75.8944 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
      minPrice: 400,
      maxPrice: 1000,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0731-2558866',
      rating: 4.7,
      reviews: [{ patientName: 'Ritu Jain', comment: 'Top class child specialist and modern rooms.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-06')
    },

    // COIMBATORE
    {
      _id: 'hosp_cbt_govt1',
      userId: 'usr_hosp_cbt_govt1',
      name: 'Coimbatore Medical College Hospital (CMCH)',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Trichy Road, Gopalapuram, Coimbatore',
      city: 'Coimbatore',
      coordinates: { lat: 11.0022, lng: 76.9723 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 30,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0422-2301393',
      rating: 4.4,
      reviews: [{ patientName: 'Ramesh Kumar', comment: 'Largest public hospital in Coimbatore, free care.', rating: 5, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-02-07')
    },
    {
      _id: 'hosp_cbt_pvt1',
      userId: 'usr_hosp_cbt_pvt1',
      name: 'Sri Ramakrishna Hospital, Coimbatore',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Sarojini Naidu Road, Siddhapudur, Coimbatore',
      city: 'Coimbatore',
      coordinates: { lat: 11.0166, lng: 76.9699 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 300,
      maxPrice: 800,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0422-4500000',
      rating: 4.7,
      reviews: [{ patientName: 'Sudha Pillai', comment: 'Excellent pediatric emergency ward and doctors.', rating: 5, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-02-08')
    },

    // NAGPUR
    {
      _id: 'hosp_nag_govt1',
      userId: 'usr_hosp_nag_govt1',
      name: 'Government Medical College (GMCH), Nagpur',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Hanuman Nagar, Medical Square, Nagpur',
      city: 'Nagpur',
      coordinates: { lat: 21.1194, lng: 79.0975 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0712-2744671',
      rating: 4.5,
      reviews: [{ patientName: 'Sanjay Deshmukh', comment: 'Very good public cardiology department.', rating: 4, createdAt: new Date('2026-05-25') }],
      createdAt: new Date('2026-02-09')
    },
    {
      _id: 'hosp_nag_pvt1',
      userId: 'usr_hosp_nag_pvt1',
      name: 'Kingsway Hospital, Nagpur',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Near Zero Mile, Nagpur',
      city: 'Nagpur',
      coordinates: { lat: 21.1511, lng: 79.0833 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
      minPrice: 500,
      maxPrice: 1200,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0712-6789100',
      rating: 4.8,
      reviews: [{ patientName: 'Vinod Agrawal', comment: 'Clean premises and top-notch critical care.', rating: 5, createdAt: new Date('2026-05-28') }],
      createdAt: new Date('2026-02-10')
    },

    // BHUBANESWAR
    {
      _id: 'hosp_bbs_govt1',
      userId: 'usr_hosp_bbs_govt1',
      name: 'AIIMS Bhubaneswar',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Sijua, Patrapada, Bhubaneswar',
      city: 'Bhubaneswar',
      coordinates: { lat: 20.2450, lng: 85.7755 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
      minPrice: 10,
      maxPrice: 100,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0674-2476789',
      rating: 4.8,
      reviews: [{ patientName: 'Debendra Mohanty', comment: 'Superb treatment at very minimal costs.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-11')
    },
    {
      _id: 'hosp_bbs_pvt1',
      userId: 'usr_hosp_bbs_pvt1',
      name: 'SUM Ultimate Medicare, Bhubaneswar',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'K-8, Kalinga Nagar, Bhubaneswar',
      city: 'Bhubaneswar',
      coordinates: { lat: 20.2911, lng: 85.7922 },
      departments: ['Cardiology', 'Pediatrics', 'General Medicine', 'Neurology', 'Orthopedics'],
      minPrice: 400,
      maxPrice: 1000,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0674-2725555',
      rating: 4.7,
      reviews: [{ patientName: 'Tanmay Misra', comment: 'Best private infrastructure and child specialists.', rating: 5, createdAt: new Date('2026-05-26') }],
      createdAt: new Date('2026-02-12')
    },

    // SURAT
    {
      _id: 'hosp_srt_govt1',
      userId: 'usr_hosp_srt_govt1',
      name: 'SMIMER Hospital, Surat',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Sahara Darwaja, Ring Road, Surat',
      city: 'Surat',
      coordinates: { lat: 21.1950, lng: 72.8450 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0261-2368040',
      rating: 4.4,
      reviews: [{ patientName: 'Bhavesh Desai', comment: 'Free operations under state low income card.', rating: 5, createdAt: new Date('2026-05-18') }],
      createdAt: new Date('2026-02-13')
    },
    {
      _id: 'hosp_srt_pvt1',
      userId: 'usr_hosp_srt_pvt1',
      name: 'Sunshine Global Hospital, Surat',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Dumas Road, Piplod, Surat',
      city: 'Surat',
      coordinates: { lat: 21.1601, lng: 72.7812 },
      departments: ['Pediatrics', 'Cardiology', 'General Medicine', 'Orthopedics'],
      minPrice: 250,
      maxPrice: 700,
      governmentSchemes: ['CGHS', 'Ayushman Bharat PM-JAY'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0261-4089999',
      rating: 4.5,
      reviews: [{ patientName: 'Karan Shah', comment: 'Great doctors and support staff.', rating: 4, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-14')
    },

    // ANAND
    {
      _id: 'hosp_and_pvt1',
      userId: 'usr_hosp_and_pvt1',
      name: 'Shree Krishna Hospital, Karamsad',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Gokal Nagar, Karamsad, Anand',
      city: 'Anand',
      coordinates: { lat: 22.5401, lng: 72.8988 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics', 'Neurology'],
      minPrice: 150,
      maxPrice: 600,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '02692-228411',
      rating: 4.6,
      reviews: [{ patientName: 'Amit Patel', comment: 'Charity trust hospital, highly affordable and top facilities.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-15')
    },

    // THANE
    {
      _id: 'hosp_tha_govt1',
      userId: 'usr_hosp_tha_govt1',
      name: 'Chhatrapati Shivaji Maharaj Hospital, Kalwa',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Kalwa, Thane, Maharashtra',
      city: 'Thane',
      coordinates: { lat: 19.2001, lng: 72.9902 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '022-25372624',
      rating: 4.3,
      reviews: [{ patientName: 'Rahul Shinde', comment: 'Government medical college hospital. Free care.', rating: 4, createdAt: new Date('2026-05-25') }],
      createdAt: new Date('2026-02-16')
    },

    // KALYAN
    {
      _id: 'hosp_kln_govt1',
      userId: 'usr_hosp_kln_govt1',
      name: 'KDMC Hospital, Kalyan',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Rambaug, Kalyan, Maharashtra',
      city: 'Kalyan',
      coordinates: { lat: 19.2399, lng: 73.1311 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: false,
      bloodAvailable: true,
      ambulanceContact: '0251-2200252',
      rating: 4.2,
      reviews: [{ patientName: 'Vijay Kulkarni', comment: 'Decent infrastructure and helpful general physician.', rating: 4, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-02-17')
    },

    // MYSORE
    {
      _id: 'hosp_mys_govt1',
      userId: 'usr_hosp_mys_govt1',
      name: 'KR Hospital (Mysore Medical College)',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Irwin Road, Mysore',
      city: 'Mysore',
      coordinates: { lat: 12.3166, lng: 76.6500 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0821-2421074',
      rating: 4.4,
      reviews: [{ patientName: 'Chandra Gowda', comment: 'Mysores biggest government hospital, free child beds.', rating: 5, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-02-18')
    },

    // HUBLI
    {
      _id: 'hosp_hub_govt1',
      userId: 'usr_hosp_hub_govt1',
      name: 'KIMS Hubli',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Vidyanagar, Hubli, Karnataka',
      city: 'Hubli',
      coordinates: { lat: 15.3647, lng: 75.1244 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics', 'Neurology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0836-2374624',
      rating: 4.5,
      reviews: [{ patientName: 'Basavaraj Patil', comment: 'Excellent neurology and critical care at low cost.', rating: 4, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-19')
    },

    // WARANGAL
    {
      _id: 'hosp_wgl_govt1',
      userId: 'usr_hosp_wgl_govt1',
      name: 'MGM Hospital, Warangal',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'MGM Road, Warangal, Telangana',
      city: 'Warangal',
      coordinates: { lat: 17.9689, lng: 79.5941 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0870-2441642',
      rating: 4.3,
      reviews: [{ patientName: 'Krishna Chary', comment: 'Helpful general medicine doctors and free scheme support.', rating: 4, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-20')
    },

    // VIJAYAWADA
    {
      _id: 'hosp_vjw_govt1',
      userId: 'usr_hosp_vjw_govt1',
      name: 'GGH Vijayawada',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Gopalareddy Road, Vijayawada',
      city: 'Vijayawada',
      coordinates: { lat: 16.5062, lng: 80.6480 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0866-2430033',
      rating: 4.4,
      reviews: [{ patientName: 'Nageswara Rao', comment: 'Aarogyasri card fully accepted. Good service.', rating: 5, createdAt: new Date('2026-05-26') }],
      createdAt: new Date('2026-02-21')
    },

    // MADURAI
    {
      _id: 'hosp_mdr_govt1',
      userId: 'usr_hosp_mdr_govt1',
      name: 'Government Rajaji Hospital, Madurai',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Panagal Road, Madurai',
      city: 'Madurai',
      coordinates: { lat: 9.9252, lng: 78.1206 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 30,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0452-2532535',
      rating: 4.5,
      reviews: [{ patientName: 'Sundar Pandian', comment: 'Very busy but doctors are experts.', rating: 4, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-22')
    },

    // JODHPUR
    {
      _id: 'hosp_jod_govt1',
      userId: 'usr_hosp_jod_govt1',
      name: 'SNMC Hospital, Jodhpur',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'Shastri Nagar, Jodhpur',
      city: 'Jodhpur',
      coordinates: { lat: 26.2739, lng: 73.0243 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0291-2434381',
      rating: 4.4,
      reviews: [{ patientName: 'Sunil Rathore', comment: 'Chiranjeevi card fully active, free medicine.', rating: 4, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-02-23')
    },

    // AJMER
    {
      _id: 'hosp_ajm_govt1',
      userId: 'usr_hosp_ajm_govt1',
      name: 'JLN Hospital, Ajmer',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Naya Bazaar, Ajmer',
      city: 'Ajmer',
      coordinates: { lat: 26.4499, lng: 74.6399 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: false,
      bloodAvailable: true,
      ambulanceContact: '0145-2443424',
      rating: 4.3,
      reviews: [{ patientName: 'Ajay Sharma', comment: 'Quick general consultation.', rating: 4, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-02-24')
    },

    // GORAKHPUR
    {
      _id: 'hosp_gkp_govt1',
      userId: 'usr_hosp_gkp_govt1',
      name: 'BRD Medical College, Gorakhpur',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Mughalpur, Gorakhpur',
      city: 'Gorakhpur',
      coordinates: { lat: 26.7606, lng: 83.3731 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 40,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0551-2501019',
      rating: 4.4,
      reviews: [{ patientName: 'Devendra Mishra', comment: 'Large pediatric wing and low price medicine.', rating: 5, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-02-25')
    },

    // VARANASI
    {
      _id: 'hosp_vns_govt1',
      userId: 'usr_hosp_vns_govt1',
      name: 'Sir Sunderlal Hospital BHU, Varanasi',
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600&auto=format&fit=crop',
      address: 'BHU Campus, Varanasi',
      city: 'Varanasi',
      coordinates: { lat: 25.2677, lng: 83.0012 },
      departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
      minPrice: 10,
      maxPrice: 80,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'CGHS'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0542-2367568',
      rating: 4.7,
      reviews: [{ patientName: 'Anil Pandey', comment: 'Excellent cardiology unit at minimal pricing.', rating: 5, createdAt: new Date('2026-05-26') }],
      createdAt: new Date('2026-02-26')
    },

    // KOZHIKODE
    {
      _id: 'hosp_cal_govt1',
      userId: 'usr_hosp_cal_govt1',
      name: 'Government Medical College, Kozhikode',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Medical College Junction, Kozhikode',
      city: 'Kozhikode',
      coordinates: { lat: 11.2741, lng: 75.8372 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0495-2350212',
      rating: 4.6,
      reviews: [{ patientName: 'Pradeep Nair', comment: 'Highly popular and free state medical benefits.', rating: 5, createdAt: new Date('2026-05-24') }],
      createdAt: new Date('2026-02-27')
    },

    // THRISSUR
    {
      _id: 'hosp_tcr_govt1',
      userId: 'usr_hosp_tcr_govt1',
      name: 'Government Medical College, Thrissur',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Mulankunnathukavu, Thrissur',
      city: 'Thrissur',
      coordinates: { lat: 10.6124, lng: 76.2024 },
      departments: ['General Medicine', 'Pediatrics', 'Orthopedics'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0487-2200310',
      rating: 4.5,
      reviews: [{ patientName: 'Haridas Menon', comment: 'Excellent pediatric team and affordable ward checkups.', rating: 4, createdAt: new Date('2026-05-25') }],
      createdAt: new Date('2026-02-28')
    },
    {
      _id: 'hosp_lko_govt2',
      userId: 'usr_hosp_lko_govt2',
      name: 'Ram Manohar Lohia Institute of Medical Sciences (RMLIMS)',
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=600&auto=format&fit=crop',
      address: 'Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      coordinates: { lat: 26.8624, lng: 81.0123 },
      departments: ['General Medicine', 'Cardiology', 'Pediatrics'],
      minPrice: 0,
      maxPrice: 30,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0522-4918504',
      rating: 4.5,
      reviews: [{ patientName: 'Aditya Sen', comment: 'Excellent and highly subsidised diagnostics.', rating: 5, createdAt: new Date('2026-05-20') }],
      createdAt: new Date('2026-03-01')
    },
    {
      _id: 'hosp_bpl_govt2',
      userId: 'usr_hosp_bpl_govt2',
      name: 'Gandhi Medical College & Hamidia Hospital',
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=600&auto=format&fit=crop',
      address: 'Sultania Road, Royal Market',
      city: 'Bhopal',
      coordinates: { lat: 23.2598, lng: 77.3995 },
      departments: ['General Medicine', 'Pediatrics', 'Cardiology'],
      minPrice: 0,
      maxPrice: 50,
      governmentSchemes: ['Ayushman Bharat PM-JAY', 'State Low-Income Health Plan'],
      emergencyService: true,
      icuAvailable: true,
      bloodAvailable: true,
      ambulanceContact: '0755-4001800',
      rating: 4.4,
      reviews: [{ patientName: 'Sudhir Vyas', comment: 'Very supportive and experienced pediatrics faculty.', rating: 4, createdAt: new Date('2026-05-22') }],
      createdAt: new Date('2026-03-02')
    }
  ],
  doctors: [
    // Legacy Doctors
    {
      _id: 'doc1',
      userId: 'usr_doc1',
      hospitalId: 'hosp1',
      name: 'Dr. Arvind Sharma',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 15,
      consultationFee: 200,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-01-12')
    },
    {
      _id: 'doc2',
      userId: 'usr_doc2',
      hospitalId: 'hosp2',
      name: 'Dr. Sneha Reddy',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 9,
      consultationFee: 300,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '02:00 PM', '03:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-13')
    },
    {
      _id: 'doc3',
      userId: 'usr_doc3',
      hospitalId: 'hosp3',
      name: 'Dr. Kabir Mehta',
      photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Neurology',
      experience: 12,
      consultationFee: 600,
      availableDays: ['Tuesday', 'Wednesday', 'Thursday'],
      availableTimeSlots: ['02:00 PM', '03:00 PM', '04:00 PM', '05:00 PM'],
      rating: 4.6,
      createdAt: new Date('2026-01-14')
    },
    {
      _id: 'doc4',
      userId: 'usr_doc1',
      hospitalId: 'hosp1',
      name: 'Dr. Rajesh Nair',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Orthopedics',
      experience: 11,
      consultationFee: 150,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '02:00 PM', '03:00 PM'],
      rating: 4.5,
      createdAt: new Date('2026-01-15')
    },

    // National Doctors (Phase 1)
    {
      _id: 'doc_del1',
      userId: 'usr_doc_del1',
      hospitalId: 'hosp_del_govt1',
      name: 'Dr. Amit Singh',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 14,
      consultationFee: 50,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.8,
      createdAt: new Date('2026-01-15')
    },
    {
      _id: 'doc_del2',
      userId: 'usr_doc_del2',
      hospitalId: 'hosp_del_pvt1',
      name: 'Dr. Rashmi Goel',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 600,
      availableDays: ['Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['02:00 PM', '03:00 PM', '04:00 PM'],
      rating: 4.9,
      createdAt: new Date('2026-01-16')
    },
    {
      _id: 'doc_mum1',
      userId: 'usr_doc_mum1',
      hospitalId: 'hosp_mum_govt1',
      name: 'Dr. Sandeep Patil',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 50,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-17')
    },
    {
      _id: 'doc_blr1',
      userId: 'usr_doc_blr1',
      hospitalId: 'hosp_blr_govt1',
      name: 'Dr. Deepa Nair',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Neurology',
      experience: 16,
      consultationFee: 100,
      availableDays: ['Monday', 'Tuesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.9,
      createdAt: new Date('2026-01-18')
    },
    {
      _id: 'doc_blr2',
      userId: 'usr_doc_blr2',
      hospitalId: 'hosp_blr_pvt1',
      name: 'Dr. Vikram Hegde',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 15,
      consultationFee: 400,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['02:00 PM', '03:00 PM', '04:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-01-19')
    },
    {
      _id: 'doc_hyd1',
      userId: 'usr_doc_hyd1',
      hospitalId: 'hosp_hyd3',
      name: 'Dr. Srinivas Rao',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 14,
      consultationFee: 300,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-01-15')
    },
    {
      _id: 'doc_hyd2',
      userId: 'usr_doc_hyd2',
      hospitalId: 'hosp_hyd2',
      name: 'Dr. Anjali Prasad',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 250,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '02:00 PM', '03:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-16')
    },
    {
      _id: 'doc_hyd3',
      userId: 'usr_doc_hyd3',
      hospitalId: 'hosp_hyd1',
      name: 'Dr. Venkat Raman',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 18,
      consultationFee: 400,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.9,
      createdAt: new Date('2026-01-17')
    },
    {
      _id: 'doc_chn1',
      userId: 'usr_doc_chn1',
      hospitalId: 'hosp_chn_govt1',
      name: 'Dr. Manian K.',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-01-23')
    },
    {
      _id: 'doc_kol1',
      userId: 'usr_doc_kol1',
      hospitalId: 'hosp_kol_govt1',
      name: 'Dr. Subrata Sen',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 13,
      consultationFee: 50,
      availableDays: ['Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-24')
    },
    {
      _id: 'doc_pune1',
      userId: 'usr_doc_pune1',
      hospitalId: 'hosp_pune_govt1',
      name: 'Dr. Prakash Joshi',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 15,
      consultationFee: 50,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-01-25')
    },
    {
      _id: 'doc_ahd1',
      userId: 'usr_doc_ahd1',
      hospitalId: 'hosp_ahd_govt1',
      name: 'Dr. Bhavesh Patel',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 40,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '02:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-26')
    },

    // National Doctors (Phase 2 - Tier 2/3 Cities)
    {
      _id: 'doc_lko1',
      userId: 'usr_doc_lko1',
      hospitalId: 'hosp_lko_pvt1',
      name: 'Dr. Manoj Gupta',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 400,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM'],
      rating: 4.6,
      createdAt: new Date('2026-01-27')
    },
    {
      _id: 'doc_jpr1',
      userId: 'usr_doc_jpr1',
      hospitalId: 'hosp_jpr_pvt1',
      name: 'Dr. Harsh Vardhan',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 500,
      availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-01-28')
    },
    {
      _id: 'doc_pat1',
      userId: 'usr_doc_pat1',
      hospitalId: 'hosp_pat_pvt1',
      name: 'Dr. Shashi Kumar',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 9,
      consultationFee: 300,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '02:00 PM', '03:00 PM'],
      rating: 4.5,
      createdAt: new Date('2026-01-29')
    },
    {
      _id: 'doc_bpl1',
      userId: 'usr_doc_bpl1',
      hospitalId: 'hosp_bpl_govt1',
      name: 'Dr. Ritu Sharma',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 50,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-01-30')
    },
    {
      _id: 'doc_chd1',
      userId: 'usr_doc_chd1',
      hospitalId: 'hosp_chd_pvt1',
      name: 'Dr. Gurpreet Singh',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 15,
      consultationFee: 600,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-01-31')
    },
    {
      _id: 'doc_gau1',
      userId: 'usr_doc_gau1',
      hospitalId: 'hosp_gau_govt1',
      name: 'Dr. Barua Baruah',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-02-01')
    },
    {
      _id: 'doc_koc1',
      userId: 'usr_doc_koc1',
      hospitalId: 'hosp_koc_pvt1',
      name: 'Dr. Thomas Mathew',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 14,
      consultationFee: 500,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '03:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-02-02')
    },
    {
      _id: 'doc_viz1',
      userId: 'usr_doc_viz1',
      hospitalId: 'hosp_viz_pvt1',
      name: 'Dr. Prasad Raju',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 13,
      consultationFee: 400,
      availableDays: ['Tuesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '02:00 PM', '03:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-02-03')
    },

    // VADODARA
    {
      _id: 'doc_vad1',
      userId: 'usr_doc_vad1',
      hospitalId: 'hosp_vad_govt1',
      name: 'Dr. Amit Patel',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Tuesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-01')
    },
    {
      _id: 'doc_vad2',
      userId: 'usr_doc_vad1',
      hospitalId: 'hosp_vad_pvt1',
      name: 'Dr. Hiren Shah',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 15,
      consultationFee: 500,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '02:00 PM'],
      rating: 4.8,
      createdAt: new Date('2026-03-02')
    },

    // INDORE
    {
      _id: 'doc_ind1',
      userId: 'usr_doc_ind1',
      hospitalId: 'hosp_ind_govt1',
      name: 'Dr. Sanjay Vyas',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 14,
      consultationFee: 20,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-03')
    },

    // COIMBATORE
    {
      _id: 'doc_cbt1',
      userId: 'usr_doc_cbt1',
      hospitalId: 'hosp_cbt_govt1',
      name: 'Dr. Rajesh K.',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 20,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.7,
      createdAt: new Date('2026-03-04')
    },

    // NAGPUR
    {
      _id: 'doc_nag1',
      userId: 'usr_doc_nag1',
      hospitalId: 'hosp_nag_govt1',
      name: 'Dr. Suresh Deshmukh',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 18,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.7,
      createdAt: new Date('2026-03-05')
    },

    // BHUBANESWAR
    {
      _id: 'doc_bbs1',
      userId: 'usr_doc_bbs1',
      hospitalId: 'hosp_bbs_govt1',
      name: 'Dr. Alok Misra',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 16,
      consultationFee: 50,
      availableDays: ['Monday', 'Tuesday', 'Thursday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.8,
      createdAt: new Date('2026-03-06')
    },

    // SURAT
    {
      _id: 'doc_srt1',
      userId: 'usr_doc_srt1',
      hospitalId: 'hosp_srt_govt1',
      name: 'Dr. Karan Desai',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-07')
    },

    // ANAND
    {
      _id: 'doc_and1',
      userId: 'usr_doc_and1',
      hospitalId: 'hosp_and_pvt1',
      name: 'Dr. Anil Shah',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 15,
      consultationFee: 200,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.8,
      createdAt: new Date('2026-03-08')
    },

    // THANE
    {
      _id: 'doc_tha1',
      userId: 'usr_doc_tha1',
      hospitalId: 'hosp_tha_govt1',
      name: 'Dr. Rahul Shinde',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-09')
    },

    // KALYAN
    {
      _id: 'doc_kln1',
      userId: 'usr_doc_kln1',
      hospitalId: 'hosp_kln_govt1',
      name: 'Dr. Vijay Kulkarni',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 25,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.4,
      createdAt: new Date('2026-03-10')
    },

    // MYSORE
    {
      _id: 'doc_mys1',
      userId: 'usr_doc_mys1',
      hospitalId: 'hosp_mys_govt1',
      name: 'Dr. Chandra Gowda',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 13,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-11')
    },

    // HUBLI
    {
      _id: 'doc_hub1',
      userId: 'usr_doc_hub1',
      hospitalId: 'hosp_hub_govt1',
      name: 'Dr. Guru Patil',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-12')
    },

    // WARANGAL
    {
      _id: 'doc_wgl1',
      userId: 'usr_doc_wgl1',
      hospitalId: 'hosp_wgl_govt1',
      name: 'Dr. Krishna Chary',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 20,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.4,
      createdAt: new Date('2026-03-13')
    },

    // VIJAYAWADA
    {
      _id: 'doc_vjw1',
      userId: 'usr_doc_vjw1',
      hospitalId: 'hosp_vjw_govt1',
      name: 'Dr. Venkat Prasad',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-14')
    },

    // MADURAI
    {
      _id: 'doc_mdr1',
      userId: 'usr_doc_mdr1',
      hospitalId: 'hosp_mdr_govt1',
      name: 'Dr. Suresh Pandian',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 20,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-15')
    },

    // JODHPUR
    {
      _id: 'doc_jod1',
      userId: 'usr_doc_jod1',
      hospitalId: 'hosp_jod_govt1',
      name: 'Dr. Sunil Rathore',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 14,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-16')
    },

    // AJMER
    {
      _id: 'doc_ajm1',
      userId: 'usr_doc_ajm1',
      hospitalId: 'hosp_ajm_govt1',
      name: 'Dr. Ajay Sharma',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 11,
      consultationFee: 20,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.4,
      createdAt: new Date('2026-03-17')
    },

    // GORAKHPUR
    {
      _id: 'doc_gkp1',
      userId: 'usr_doc_gkp1',
      hospitalId: 'hosp_gkp_govt1',
      name: 'Dr. Devendra Mishra',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 13,
      consultationFee: 25,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-18')
    },

    // VARANASI
    {
      _id: 'doc_vns1',
      userId: 'usr_doc_vns1',
      hospitalId: 'hosp_vns_govt1',
      name: 'Dr. Anil Pandey',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 15,
      consultationFee: 40,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.7,
      createdAt: new Date('2026-03-19')
    },

    // KOZHIKODE
    {
      _id: 'doc_cal1',
      userId: 'usr_doc_cal1',
      hospitalId: 'hosp_cal_govt1',
      name: 'Dr. Pradeep Nair',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 14,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-20')
    },

    // THRISSUR
    {
      _id: 'doc_tcr1',
      userId: 'usr_doc_tcr1',
      hospitalId: 'hosp_tcr_govt1',
      name: 'Dr. Haridas Menon',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 12,
      consultationFee: 30,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.5,
      createdAt: new Date('2026-03-21')
    },
    {
      _id: 'doc_lko_govt2_1',
      userId: 'usr_doc_lko_govt2_1',
      hospitalId: 'hosp_lko_govt2',
      name: 'Dr. Rakesh Shukla',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=300&auto=format&fit=crop',
      specialization: 'Cardiology',
      experience: 14,
      consultationFee: 20,
      availableDays: ['Monday', 'Tuesday', 'Wednesday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM'],
      rating: 4.6,
      createdAt: new Date('2026-03-22')
    },
    {
      _id: 'doc_bpl_govt2_1',
      userId: 'usr_doc_bpl_govt2_1',
      hospitalId: 'hosp_bpl_govt2',
      name: 'Dr. Megha Sharma',
      photo: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?q=80&w=300&auto=format&fit=crop',
      specialization: 'Pediatrics',
      experience: 10,
      consultationFee: 15,
      availableDays: ['Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
      rating: 4.5,
      createdAt: new Date('2026-03-23')
    }
  ],
  appointments: [
    {
      _id: 'appt1',
      appointmentId: 'BAD-2026-7789',
      patientId: 'pat1',
      doctorId: 'doc1',
      hospitalId: 'hosp1',
      date: new Date('2026-05-22'),
      timeSlot: '10:00 AM',
      reason: 'Regular heart review checkup',
      status: 'confirmed',
      notes: 'Patient should carry previous reports.',
      consultationType: 'in-person',
      createdAt: new Date('2026-05-18')
    },
    {
      _id: 'appt2',
      appointmentId: 'BAD-2026-8890',
      patientId: 'pat1',
      doctorId: 'doc1',
      hospitalId: 'hosp1',
      date: new Date('2026-06-18'),
      timeSlot: '11:00 AM',
      reason: 'Follow-up consultation on chest pain',
      status: 'confirmed',
      notes: 'Please join the video call on time.',
      consultationType: 'video',
      createdAt: new Date('2026-06-18')
    }
  ],
  healthRecords: [
    {
      _id: 'rec1',
      patientId: 'pat1',
      title: 'ECG Report Jan 2026',
      type: 'report',
      fileUrl: 'data:application/pdf;base64,JVBERi0xLjQKJ...',
      notes: 'Slightly high heart rate observed during running.',
      uploadedAt: new Date('2026-01-20')
    }
  ],
  prescriptions: [
    {
      _id: 'pres1',
      appointmentId: 'appt1',
      patientId: 'pat1',
      doctorId: 'doc1',
      date: new Date('2026-05-22'),
      medicines: [
        { name: 'Atenolol', dosage: '25mg', frequency: 'Once daily (Morning)', duration: '30 Days' },
        { name: 'Ecosprin', dosage: '75mg', frequency: 'Once daily (Night)', duration: '30 Days' }
      ],
      advice: 'Avoid oily and spicy foods. Do light morning walking for 20 minutes.'
    }
  ]
};

// CRUD Helper Methods to emulate Mongoose in controllers
const mockStoreHelpers = {
  find: (collection, filterFn) => {
    return mockStore[collection].filter(filterFn || (() => true));
  },
  findOne: (collection, filterFn) => {
    return mockStore[collection].find(filterFn) || null;
  },
  findById: (collection, id) => {
    return mockStore[collection].find(item => item._id === id) || null;
  },
  create: (collection, data) => {
    const newDoc = {
      _id: `mock_${collection}_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
      createdAt: new Date(),
      ...data
    };
    mockStore[collection].push(newDoc);
    return newDoc;
  },
  findByIdAndUpdate: (collection, id, updateData) => {
    const idx = mockStore[collection].findIndex(item => item._id === id);
    if (idx === -1) return null;
    mockStore[collection][idx] = {
      ...mockStore[collection][idx],
      ...updateData
    };
    return mockStore[collection][idx];
  },
  findByIdAndDelete: (collection, id) => {
    const idx = mockStore[collection].findIndex(item => item._id === id);
    if (idx === -1) return null;
    const removed = mockStore[collection][idx];
    mockStore[collection].splice(idx, 1);
    return removed;
  }
};

module.exports = { mockStore, mockStoreHelpers };
